---
- name: Install web server on EC2 
  hosts: mywebserver
  become: true

  tasks:
    - name: update the local Apache httpd package
      ansible.builtin.yum:
        name: httpd
        state: update
    - name: Ensure apache is at the latest version
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: httpd service enabled  
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
